### ISSUE TITLE
Artifact name

### ISSUE THREAD

**Issue by HerbertKoelman** [hypertino/inflector#4]
Hello, I'm a happy user of your work, but I'm a bit confused by your naming conventions. I expected to find one artifactId named inflector. 

But I found:
- inflector_2.12
- inflector_sjs0.6_2.10
- ...

What is the difference between these artifacts ? Which one should I use in my java project ?

**Comment by maqdev** [comment]
Hi! Actually it's standard naming when it's cross-compiled with `Scala` + `Scala.js`.

If you're Scala user, you only have to add it like `libraryDependencies += "com.hypertino" %% "inflector" % "1.0.6"`
However if you're using it in Java, then you may use `inflector_2.12` or `inflector_2.11` versions (those are built with Scala 2.12 and Scala 2.11 correspondingly).
Artifacts with `sjs` are for Scala.JS

**Comment by HerbertKoelman** [comment]
Cool, thanks
